### ISSUE TITLE
Ability to import external (versioned) packages inside preset

### ISSUE THREAD

**Issue by jcao02** [preset/preset#107]
## Summary

Hi @innocenzi !

We've started to use your project in my company recently (very nice job!), and we've found that [the constraints](https://preset.dev/concepts/preset-file.html#constraints) that forbids from importing external libraries limits considerably the code reuse capabilities (which is the main reason why we think it's a good fit to scaffold our projects)

The limitations come mainly from:
1. Being able to write more sophisticated actions by leveraging existing libraries
2. Avoid reinventing the wheel by sharing common actions across different presets repositories
3. Version actions and presets so we can evolve them alongside the boilerplate they generate/modify

Do you think we can enable this somehow?

## Use-cases

Some of the use-cases that would benefit from this are:

1. Using [jscodeshift](https://github.com/facebook/jscodeshift) or similar codemod libraries to modify existing boilerplate
2. Using template languages like [ejs](ejs.co) to interpolate user input strings inside templates
3. Create and share framework specific actions to manipulate configuration files (e.g. `nuxt.config.js`, `vue.config.ja`, `next.config.js`, `webpack.config.js`) -- this is a core use-case if we want to extend a framework's functionality through this library

And all of these could be done without modifying the core and CLI packages.

## Short-term proposal

Perhaps one potential short-term solution is to install dependencies after cloning the repository [here](https://github.com/preset/preset/blob/a7ea780c623a0b95d96725bea8d9f00c47251928/packages/core/src/resolve.ts#L290) and keep a cache of the preset repo somewhere in the filesystem so we don't have to re-install every time we run it -- This way performance is only harmed the first time the preset is used, which I think is a more than acceptable trade-off for the code reusability capabilities we'll gain.

We could also make this behaviour opt-in with a parameter on the CLI. What do you think?

**Comment by innocenzi** [comment]
Hey!

I planned to do this in the early version of this project (see https://github.com/preset/preset/issues/7, it was before the second rewrite of the project). I ended up not implementing that because it was some work for something I would not even use myself. 

While I see the benefits of allowing the use of 3rd-party library, keep in mind that the implementation for its support would not be trivial, as I currently use [`vm`](https://nodejs.org/api/vm.html) to be able to run the preset without installing dependencies. The ability to not `import` the action functions comes from the `context` of `vm`, and the rest of the library is also designed around that. 

For this reason, while I'm completely open to the feature, I won't be able to implement it myself, because I don't really have the bandwidth right now. If you're willing to PR it, I'll happily review it and merge it.
