### ISSUE TITLE
feat: sort dependencies & devDependencies's key in package.json file

### ISSUE THREAD

**Issue by ycs77** [preset/preset#45]
I wish the order of `dependencies` is correct. But still respect your ideas, can you implement this feature?

---

Lodash code of sort object with key (Refrence: https://github.com/lodash/lodash/issues/1459#issuecomment-253969771):

```js
_(obj).toPairs().sortBy(0).fromPairs().value()
```

**Comment by ycs77** [comment]
The sorting method I currently is using yarn upgrade/npm update to sort dependencies key:

```js
const { Preset } = require('use-preset')
const spawn = require('cross-spawn')

const hasYarn = spawn.sync('yarn', ['--version']).status === 0

// prettier-ignore
module.exports = Preset.make('Laravel Tailwind CSS')
  .option('interaction', true)

  // ...

  .installDependencies()
    .if(({ flags }) => Boolean(flags.interaction))
    .for('node')
    .title('Install node dependencies')
    .chain()

  .run(hasYarn ? 'yarn' : 'npm', [hasYarn ? 'upgrade' : 'update'])
```

What do you think?

**Comment by innocenzi** [comment]
Hello,

I'm not against this feature, but I wonder where you would like it to be. In the `install-dependencies` action? Or the `edit-json` action?

**Comment by ycs77** [comment]
I think must in `edit-json` action sort, auto sort dependencies & devDependencies after the` merge` method.

**Comment by innocenzi** [comment]
I might introduce a new `edit-dependencies` action then, or add a specific rule for checking if the file is `package.json`, and sort the `dependencies` and `devDependencies` after. 

I'll think about it, if you have any other idea let me know :)

**Comment by innocenzi** [comment]
Yeah, after thinking about it and trying it locally, I'll definitely implement this, but in a new action, as I said. I don't plan on creating that action right now though, it will probably be after the 1.0 release. 

The reason I'm going with a new action is that I don't want a specific rule looking for `dependencies`, `devDependencies`, `require` and `require-dev` in an action that is not meant to be for only editing `package.json` and `composer.json` files. I'd rather have an `edit-node-dependencies` and `edit-php-dependencies` with specific features in them, but since it's not a priority (since `edit-json` works fine) and it's still quite some work, I'll delay that a bit.

**Comment by ycs77** [comment]
Thanks for taking the time to respond. Looking forward to this feature! **Preset** is a good tool, it saves me time, thanks for your work! 😍
